language: java
dist: trusty

before_install:
 - chmod +x gradlew

android:
  components:
    # The latest revision of Android SDK Tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-28
